export const artworks = {
  main: [
    "main/inainaswim.jpg",
    "main/inafang.jpg",
    "main/inainabunni.jpg",
    "main/dragoonin.jpg",
    "main/chrinas.jpg",
    "main/inaked.jpg",
    "main/inashort.jpg",
    "main/mona.jpg",
    "main/orichara2.jpg",
    "main/petra-snow.jpg",
    "main/snow.jpg",
    "main/menhera.jpg",
    "main/kaibd.jpg",
    "main/emopurin.jpg",
    "main/orichara.jpg",
    "main/nekonoeru.jpg",
    "main/tmt.jpg",
    "main/petraneko.jpg",
    "main/monasummer.jpg",
    "main/petra.jpg",
    "main/dogson.jpg",
    "main/melchan.jpg",
    "main/calliopaint.jpg",
    "main/monyan.jpg",
    "main/uto.jpg",
    "main/hotpurin.jpg",
    "main/miobday.jpg",
    "main/noshiro.jpg",
  ],
  old: [
    "main/rei.jpg",
    "main/2b.jpg",
    "main/carbonmonoxide.jpg",
    "main/coop.jpg",
    "main/marzia.jpg",
  ],
  extra: [
    "main/emptiness_and_helplessness.jpg",
    "main/i_dont_love.jpg",
  ],
  tv: [
    "tv/lit.jpg",
    "tv/breakingbad.jpg",
    "tv/arrival.jpg",
    "tv/mrrobot.jpg",
    "tv/poi.jpg",
  ]
}