services:

  web:
    build: .
    env_file:
      - .env
    ports:
      - ${DEV_PORT:-8080}:5173
      - ${BUILD_PORT:-8081}:4173 # build preview
    volumes:
      - ./:/usr/src/app
    # networks:
    #   - vue

# networks:
#   vue:
#     driver: bridge